using System.Text;
using SimpleLangCompiler.FrontEnd;
using Xunit.Abstractions;

namespace TestSimpleLangCompiler;

/// <summary>
///     Note: this test cases have been autogenerated using an LLM
/// </summary>
public class SemanticTests(ITestOutputHelper output)
{
    private void SemOk(string input)
    {
        var stream = new MemoryStream(Encoding.UTF8.GetBytes(input));
        var parser = new Parser(new Scanner(stream));
        var sw = new StringWriter();
        parser.errors.errorStream = sw;
        
        parser.Parse();

        output.WriteLine(sw.ToString());
        
        if (parser.errors.synCount > 0)
        {
            throw new Exception("Syntax error");    
        }
        
        Assert.Equal(0, parser.errors.count);
    }

    private void SemErr(string input)
    {
        
        var stream = new MemoryStream(Encoding.UTF8.GetBytes(input));
        var parser = new Parser(new Scanner(stream));
        var sw = new StringWriter();
        parser.errors.errorStream = sw;
        
        parser.Parse();

        output.WriteLine(sw.ToString());
        
        if (parser.errors.synCount > 0)
        {
            throw new Exception("Syntax error");    
        }
        
        Assert.True(parser.errors.count > 0);
    }
    
    // =========================
    // Valid programs
    // =========================
 
    [Fact]
    public void ValidIntAssignment() => SemOk(@"
        fn main() {
            var x: int;
            x = 5;
        }
    ");
 
    [Fact]
    public void ValidCharAssignment() => SemOk(@"
        fn main() {
            var c: char;
            c = 'a';
        }
    ");
 
    [Fact]
    public void ValidArithmeticExpression() => SemOk(@"
        fn main() {
            var x: int;
            x = 1 + 2 * 3;
        }
    ");
 
    [Fact]
    public void ValidComparison() => SemOk(@"
        fn main() {
            if (1 < 2) {
                return;
            }
        }
    ");
 
    [Fact]
    public void ValidFunctionCallTypes() => SemOk(@"
        fn foo(a: int, b: int) {
            return;
        }
 
        fn main() {
            foo(1, 2);
        }
    ");
    
    [Fact]
    public void ValidFunctionTypes() => SemOk(@" 
        fn foo(a: int, b: int, c: int) {
            a = a + 1;
            b = b + 1;
            c = a + b;
        }

        fn main() {
            foo(1, 2, 3);
        }
    ");
 
    [Fact]
    public void ValidReturnType() => SemOk(@"
        fn foo(): int {
            return 5;
        }
    ");
 
    [Fact]
    public void ValidCharComparison() => SemOk(@"
        fn main() {
            if ('a' = 'b') {
                return;
            }
        }
    ");
 
    [Fact]
    public void ValidSimpleAssignment() => SemOk(@"
        var x: int;
 
        fn main() {
            x = 5;
        }
    ");
 
    [Fact]
    public void ValidFunctionParams() => SemOk(@"
        fn add(a: int, b: int): int {
            return a;
        }
    ");
 
    [Fact]
    public void ValidShadowing() => SemOk(@"
        var x: int;
 
        fn main() {
            var x: int;
            x = 10;
        }
    ");
 
    [Fact]
    public void ValidNestedScope() => SemOk(@"
        fn main() {
            var x: int;
            var y: int;
 
            if (1 = 1) {
                y = 5;
            }
 
            x = 3;
        }
    ");
 
    [Fact]
    public void ValidFunctionCall() => SemOk(@"
        fn foo(a: int, b: int) {
            return;
        }
 
        fn main() {
            foo(1, 2);
        }
    ");
 
    [Fact]
    public void ValidRecursiveFunction() => SemOk(@"
        fn fact(n: int): int {
            if (n = 0) {
                return 1;
            } else {
                return n;
            }
        }
    ");
 
    [Fact]
    public void ValidWhile() => SemOk(@"
        fn main() {
            var x: int;
            x = 0;
 
            while (x < 10) {
                x = x + 1;
            }
        }
    ");
 
    // =========================
    // Invalid programs
    // =========================
 
    [Fact]
    public void ErrorUndefinedVariable() => SemErr(@"
        fn main() {
            x = 5;
        }
    ");
 
    [Fact]
    public void ErrorDuplicateVariable() => SemErr(@"
        fn main() {
            var x: int;
            var x: int;
        }
    ");
 
    [Fact]
    public void ErrorDuplicateFunction() => SemErr(@"
        fn foo() {
            return;
        }
        fn foo() {
            return;
        }
    ");
 
    [Fact]
    public void ErrorUndefinedFunctionCall() => SemErr(@"
        fn main() {
            foo(1);
        }
    ");
 
    [Fact]
    public void ErrorWrongArgumentCount() => SemErr(@"
        fn foo(a: int, b: int) {
            return;
        }
 
        fn main() {
            foo(1);
        }
    ");
 
    [Fact]
    public void ErrorVariableNotGlobal() => SemErr(@"
        fn foo() {
            var x: int;
        }
 
        fn main() {
            x = 5;
        }
    ");
 
    [Fact]
    public void ErrorDuplicateParameter() => SemErr(@"
        fn foo(a: int, a: int) {
            return;
        }
    ");
 
    [Fact]
    public void ErrorParamLocalConflict() => SemErr(@"
        fn foo(a: int) {
            var a: int;
        }
    ");
 
    [Fact]
    public void ErrorAssignToFunction() => SemErr(@"
        fn foo() {
            return;
        }
 
        fn main() {
            foo = 5;
        }
    ");
 
    [Fact]
    public void ErrorCallVariableAsFunction() => SemErr(@"
        var x: int;
 
        fn main() {
            x(1);
        }
    ");
 
    [Fact]
    public void ErrorMultipleErrors() => SemErr(@"
        fn main() {
            x = 5;
            y = 6;
            foo(1);
        }
    ");
 
    [Fact]
    public void ErrorAssignCharToInt() => SemErr(@"
        fn main() {
            var x: int;
            x = 'a';
        }
    ");
 
    [Fact]
    public void ErrorAssignIntToChar() => SemErr(@"
        fn main() {
            var c: char;
            c = 5;
        }
    ");
 
    [Fact]
    public void ErrorArithmeticWithChar() => SemErr(@"
        fn main() {
            var x: int;
            x = 'a' + 1;
        }
    ");
 
    [Fact]
    public void ErrorMixedComparison() => SemErr(@"
        fn main() {
            if (1 = 'a') {
                return;
            }
        }
    ");
 
    [Fact]
    public void ErrorWrongArgumentType() => SemErr(@"
        fn foo(a: int) {
            return;
        }
 
        fn main() {
            foo('a');
        }
    ");
 
    [Fact]
    public void ErrorWrongReturnType() => SemErr(@"
        fn foo(): int {
            return 'a';
        }
    ");
 
    [Fact]
    public void ErrorMissingReturnValue() => SemErr(@"
        fn foo(): int {
            return;
        }
    ");
 
    [Fact]
    public void ErrorUnexpectedReturnValue() => SemErr(@"
        fn foo() {
            return 5;
        }
    ");
 
    [Fact]
    public void ErrorBinaryOpTypeMismatch() => SemErr(@"
        fn main() {
            var x: int;
            x = 1 + 'a';
        }
    ");
 
    [Fact]
    public void ErrorFunctionArgumentMismatchMultiple() => SemErr(@"
        fn foo(a: int, b: char) {
            return;
        }
 
        fn main() {
            foo(1, 2);
        }
    ");
}