using System.Text;
using SimpleLangCompiler.FrontEnd;
using Xunit.Abstractions;

namespace TestSimpleLangCompiler;

/// <summary>
///     Note: this test cases have been autogenerated using an LLM
/// </summary>
public class SemanticTests(ITestOutputHelper output)
{
    private void SemOk(string input)
    {
        var stream = new MemoryStream(Encoding.UTF8.GetBytes(input));
        var parser = new Parser(new Scanner(stream));
        var sw = new StringWriter();
        parser.Errors.ErrorStream = sw;

        parser.Parse();

        output.WriteLine(sw.ToString());

        if (parser.Errors.SynCount > 0)
        {
            throw new Exception("Syntax error");
        }

        Assert.Equal(0, parser.Errors.Count);
    }

    private void SemErr(string input)
    {
        var stream = new MemoryStream(Encoding.UTF8.GetBytes(input));
        var parser = new Parser(new Scanner(stream));
        var sw = new StringWriter();
        parser.Errors.ErrorStream = sw;

        parser.Parse();

        output.WriteLine(sw.ToString());

        if (parser.Errors.SynCount > 0)
        {
            throw new Exception("Syntax error");
        }

        // TODO also check the content of the error message
        Assert.True(parser.Errors.Count > 0);
    }

    #region ValidPrograms
    
    // =========================
    // Valid programs
    // =========================
    
    [Fact]
    public void ValidLargeProgram() => SemOk(@"
        var i: int;

        fn putInt(x: int): void { /* largest printable number = 9999 */
            var c0: char;
            var c1: char;
            var c2: char;
            var c3: char;

            c3 = CHR(48 + x % 10); x = x / 10;
            c2 = CHR(48 + x % 10); x = x / 10;
            c1 = CHR(48 + x % 10); x = x / 10;
            c0 = CHR(48 + x % 10);

            if (c0 > '0') { put(c0); put(c1); put(c2); }
            elseif (c1 > '0') { put(c1); put(c2); }
            elseif (c2 > '0') { put(c2); }
            put(c3);
        }

        fn main(): void { /* print odd numbers */
            i = 1;
            while (i < 100) {
                putInt(i);
                putLn();
                i = i + 2;
            }
        }
    ");

    [Fact]
    public void ValidIntAssignment() => SemOk(@"
        fn main() {
            var x: int;
            x = 5;
        }
    ");

    [Fact]
    public void ValidCharAssignment() => SemOk(@"
        fn main() {
            var c: char;
            c = 'a';
        }
    ");

    [Fact]
    public void ValidArithmeticExpression() => SemOk(@"
        fn main() {
            var x: int;
            x = 1 + 2 * 3;
        }
    ");

    [Fact]
    public void ValidComparison() => SemOk(@"
        fn main() {
            if (1 < 2) {
                return;
            }
        }
    ");

    [Fact]
    public void ValidFunctionCallTypes() => SemOk(@"
        fn foo(a: int, b: int) {
            return;
        }
 
        fn main() {
            foo(1, 2);
        }
    ");

    [Fact]
    public void ValidFunctionTypes() => SemOk(@" 
        fn foo(a: int, b: int, c: int) {
            a = a + 1;
            b = b + 1;
            c = a + b;
        }

        fn main() {
            foo(1, 2, 3);
        }
    ");

    [Fact]
    public void ValidReturnType() => SemOk(@"
        fn foo(): int {
            return 5;
        }
    ");

    [Fact]
    public void ValidCharComparison() => SemOk(@"
        fn main() {
            if ('a' = 'b') {
                return;
            }
        }
    ");

    [Fact]
    public void ValidSimpleAssignment() => SemOk(@"
        var x: int;
 
        fn main() {
            x = 5;
        }
    ");

    [Fact]
    public void ValidFunctionParams() => SemOk(@"
        fn add(a: int, b: int): int {
            return a;
        }
    ");

    [Fact]
    public void ValidShadowing() => SemOk(@"
        var x: int;
 
        fn main() {
            var x: int;
            x = 10;
        }
    ");

    [Fact]
    public void ValidNestedScope() => SemOk(@"
        fn main() {
            var x: int;
            var y: int;
 
            if (1 = 1) {
                y = 5;
            }
 
            x = 3;
        }
    ");

    [Fact]
    public void ValidFunctionCall() => SemOk(@"
        fn foo(a: int, b: int) {
            return;
        }
 
        fn main() {
            foo(1, 2);
        }
    ");

    [Fact]
    public void ValidBuiltInFunctionCalls() => SemOk(@"
        fn main() {
            var x: int;
            var a: char;
            
            put('a');
            putLn();
            x = ORD('a');
            a = CHR(x);
        }
    ");

    [Fact]
    public void ValidRecursiveFunction() => SemOk(@"
        fn fact(n: int): int {
            if (n = 0) {
                return 1;
            } else {
                return n;
            }
        }
    ");

    [Fact]
    public void ValidWhile() => SemOk(@"
        fn main() {
            var x: int;
            x = 0;
 
            while (x < 10) {
                x = x + 1;
            }
        }
    ");

    [Fact]
    public void ValidFunctionAddOp() => SemOk(@"
        fn foo(): int {
            return 1;
        }

        fn bar(a: int, b: int): int {
            return a + b;        
        }

        fn main() {
            var x: int;
            x = foo() + bar(1, 2);
        }
    ");
    
    #endregion

    #region InvalidPrograms

    // =========================
    // Invalid programs
    // =========================
    
    [Fact]
    public void ErrorUndefinedVariable() => SemErr(@"
        fn main() {
            x = 5;
        }
    ");

    [Fact]
    public void ErrorDuplicateVariable() => SemErr(@"
        fn main() {
            var x: int;
            var x: int;
        }
    ");

    [Fact]
    public void ErrorDuplicateFunction() => SemErr(@"
        fn foo() {
            return;
        }
        fn foo() {
            return;
        }
    ");

    [Fact]
    public void ErrorUndefinedFunctionCall() => SemErr(@"
        fn main() {
            foo(1);
        }
    ");

    [Fact]
    public void ErrorWrongArgumentCount() => SemErr(@"
        fn foo(a: int, b: int) {
            return;
        }
 
        fn main() {
            foo(1);
        }
    ");

    [Fact]
    public void ErrorVariableNotGlobal() => SemErr(@"
        fn foo() {
            var x: int;
            return;
        }
 
        fn main() {
            x = 5;
        }
    ");

    [Fact]
    public void ErrorDuplicateParameter() => SemErr(@"
        fn foo(a: int, a: int) {
            return;
        }
    ");

    [Fact]
    public void ErrorParamLocalConflict() => SemErr(@"
        fn foo(a: int) {
            var a: int;
        }
    ");

    [Fact]
    public void ErrorAssignToFunction() => SemErr(@"
        fn foo() {
            return;
        }
 
        fn main() {
            foo = 5;
        }
    ");

    [Fact]
    public void ErrorAssignVarToFunction() => SemErr(@"
        fn foo(): int {
            return 1;
        }
 
        fn main() {
            var x: int;
            foo = x;
        }
    ");

    [Fact]
    public void ErrorAssignToFunctionCorrectType() => SemErr(@"
        fn foo(): int {
            return;
        }
 
        fn main() {
            foo = 5;
        }
    ");

    [Fact]
    public void ErrorMultipleErrors() => SemErr(@"
        fn main() {
            x = 5;
            y = 6;
            foo(1);
        }
    ");

    [Fact]
    public void ErrorAssignCharToInt() => SemErr(@"
        fn main() {
            var x: int;
            x = 'a';
        }
    ");

    [Fact]
    public void ErrorAssignIntToChar() => SemErr(@"
        fn main() {
            var c: char;
            c = 5;
        }
    ");

    [Fact]
    public void ErrorArithmeticWithChar() => SemErr(@"
        fn main() {
            var x: int;
            x = 'a' + 1;
        }
    ");

    [Fact]
    public void ErrorMixedComparison() => SemErr(@"
        fn main() {
            if (1 = 'a') {
                return;
            }
        }
    ");

    [Fact]
    public void ErrorWrongArgumentType() => SemErr(@"
        fn foo(a: int) {
            return;
        }
 
        fn main() {
            foo('a');
        }
    ");

    [Fact]
    public void ErrorWrongReturnType() => SemErr(@"
        fn foo(): int {
            return 'a';
        }
    ");

    [Fact]
    public void ErrorMissingReturnValue() => SemErr(@"
        fn foo(): int {
            return;
        }
    ");

    [Fact]
    public void ErrorUnexpectedReturnValue() => SemErr(@"
        fn foo() {
            return 5;
        }
    ");

    [Fact]
    public void ErrorBinaryOpTypeMismatch() => SemErr(@"
        fn main() {
            var x: int;
            x = 1 + 'a';
        }
    ");

    [Fact]
    public void ErrorFunctionArgumentMismatchMultiple() => SemErr(@"
        fn foo(a: int, b: char) {
            return;
        }
 
        fn main() {
            foo(1, 2);
        }
    ");

    [Fact]
    public void ErrorReturnTypeMismatchIntVsChar() => SemErr(@"
        fn foo(): char {
            return 5;
        }
    ");

    [Fact]
    public void ErrorAssignFunctionReturnToWrongType() => SemErr(@"
        fn foo(): int {
            return 1;
        }

        fn main() {
            var c: char;
            c = foo();
        }
    ");

    [Fact]
    public void ErrorNestedCallWrongArgType() => SemErr(@"
        fn foo(a: int): int {
            return a;
        }

        fn main() {
            var x: int;
            x = foo(foo('a'));
        }
    ");

    [Fact]
    public void ErrorCallWithTooManyArgs() => SemErr(@"
        fn foo(a: int) {
            return;
        }

        fn main() {
            foo(1, 2);
        }
    ");

    [Fact]
    public void ErrorCallWithNoArgsWhenExpected() => SemErr(@"
        fn foo(a: int) {
            return;
        }

        fn main() {
            foo();
        }
    ");

    [Fact]
    public void ErrorGlobalVarDuplicate() => SemErr(@"
        var x: int;
        var x: int;

        fn main() {
            x = 1;
        }
    ");

    [Fact]
    public void ErrorReturnValueInVoidNestedFunction() => SemErr(@"
        fn helper() {
            return 1;
        }

        fn main() {
            helper();
        }
    ");

    [Fact]
    public void ErrorCharArithmeticAssignedToInt() => SemErr(@"
        fn main() {
            var x: int;
            x = 'a' * 2;
        }
    ");

    [Fact]
    public void ErrorCompareMismatchInWhile() => SemErr(@"
        fn main() {
            var x: int;
            while (x < 'a') {
                x = x + 1;
            }
        }
    ");
    
    #endregion
}